
language: python

cache: pip

os:
  - linux

branches:
  only:
  - master

matrix:
  include:
    - python: 3.7.3
      dist: xenial
      sudo: true

before_install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python3; export PATH="/c/Python37:/c/Python37/Scripts:$PATH"; fi
  - python -m pip install --upgrade pip

install:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/eric
    - pip install --upgrade pip setuptools
    - pip install -r Requirements/requirements-dev-local.txt

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then dev/run_tests.bat; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; 
    then
    echo PWD - "$PWD";
    ls;
    echo TRAVIS_BUILD_DIR "$TRAVIS_BUILD_DIR";
    ./dev/run_tests.sh;
    fi

after_success:
  - codecov
