
language: python

cache: pip

#os:
#  - linux
#  - windows

branches:
  only:
  - master

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7.3"

matrix:
    include:
        - os: linux
          dist: xenial
          sudo: true
        - os: windows
          language: sh

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ];
    then
      choco install python3;
      export PATH="/c/Python37:/c/Python37/Scripts:$PATH";
    fi
  - python -m pip install --upgrade pip

install:
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then pip install --upgrade pip setuptools --user; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install --upgrade pip setuptools; fi
    - pip install -r Requirements/requirements-dev-local.txt

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then dev/run_tests.bat; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; 
    then
      echo PWD - "$PWD";
      ls;
      echo TRAVIS_BUILD_DIR "$TRAVIS_BUILD_DIR";
      ./dev/run_tests.sh;
    fi

after_success:
  - codecov
