
language: python

cache: pip

#os:
#  - linux
#  - windows

branches:
  only:
  - master

matrix:
    include:
        - os: linux
          python: "3.7.3"
          dist: xenial
          sudo: true
        - os: windows
          language: sh
          python: "3.7.3"
          before_install:
                - choco install python3
                - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

before_install:
  - python -m pip install --upgrade pip

install:
    - pip install --upgrade pip setuptools --user
    - pip install -r Requirements/requirements-dev-local.txt

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then dev/run_tests.bat; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; 
    then
      echo PWD - "$PWD";
      ls;
      echo TRAVIS_BUILD_DIR "$TRAVIS_BUILD_DIR";
      ./dev/run_tests.sh;
    fi

after_success:
  - codecov
