
language: python

cache: pip

branches:
  only:
  - master

matrix:
  include:
#    - os: linux
#      dist: xenial
#      python: "3.5"
#    - os: linux
#      dist: xenial
#      python: "3.6"
#    - os: linux
#      dist: xenial
#      python: "3.7.3"
    - os: windows
      language: sh
      python: "3.5"
#    - os: windows
#      language: sh
#      python: "3.6"
#    - os: windows
#      language: sh
#      python: "3.7.3"

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ];
    then
      choco install python --version=3.5;
      export PATH="/c/Python37:/c/Python37/Scripts:$PATH";
    fi

install:
  - echo "Python Version"
  - python --version --version
  - python -m pip install --upgrade pip
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then pip install --upgrade pip setuptools --user; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install --upgrade pip setuptools; fi
  - pip install -r Requirements/requirements-dev-local.txt

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ];
    then 
      dev/run_tests.bat;
      dev/run_linters.bat;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then
      echo PWD - "$PWD";
      ls;
      echo TRAVIS_BUILD_DIR "$TRAVIS_BUILD_DIR";
      ./dev/run_tests.sh;
      dev/run_linters.sh;
    fi

after_success:
  - codecov
