# https://docs.travis-ci.com/user/job-lifecycle/


#- Run Multiple Jobs/Matrixes with different python versions,
#  -> Matrix Defined
#- Different Databases
#  -> Env Defined
#- Tox Jobs only Responsible for Testing
#- Main Environment - Latest Django, Runs Dev Environment  



language: python

#env:
#- DJANGO_DB=SQLITE
#- DJANGO_DB=POSTGRES

cache: pip


#python:
  - '3.8'
  - '3.7'
  - '3.6'

jobs:
  include:
    - stage: "Testing"
      name: 'Python 3.8 - Current Dev and Release'
      python: '3.8'
      env: 
      - DJANGO_DB=SQLITE
      #- FORCE_FAIL=TRUE
    - stage: Lint and Code Style
      python: 3.8
      env: TOXENV=flake8
      #script: # Nothing to do

before_install:
- echo PHASE - before_install
- printenv

install:
- echo PHASE - install
#- pip install tox-travis
- pip install tox

before_script:
- echo PHASE - before_script

script:
- echo PHASE - script
- if [ "$FORCE_FAIL" = "TRUE" ]; then exit 1; fi
- tox
- pip list

after_success:
- echo PHASE - after_success

after_failure:
- echo PHASE - after_failure

before_deploy:
- echo PHASE - before_deploy

deploy:
- echo PHASE - deploy

after_deploy:
- echo PHASE - after_deploy
