
language: python

cache: pip

branches:
  only:
  - master

# choco supported Python Versions at https://chocolatey.org/packages/python3

matrix:
  include:
    - os: linux
      dist: xenial
      python: "3.5"
    - os: linux
      dist: xenial
      python: "3.6"
    - os: linux
      dist: xenial
      python: "3.7.3"
    - os: windows
      language: sh
      python: "3.5.4 (x32)"
      before_install: choco install python --version=3.5.4 --x86
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    - os: windows
      language: sh
      python: "3.5.4 (x64)"
      before_install: choco install python --version=3.5.4
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    - os: windows
      language: sh
      python: "3.6.8 (x32)"
      before_install: choco install python --version=3.6.8 --x86
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - os: windows
      language: sh
      python: "3.6.8 (x64)"
      before_install: choco install python --version=3.6.8
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - os: windows
      language: sh
      python: "3.7.3 (x32)"
      before_install: choco install python --version=3.7.3 --x86
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - os: windows
      language: sh
      python: "3.7.3 (x64)"
      before_install: choco install python --version=3.7.3
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - echo "Python Version"
  - python --version --version
  - python -m pip install --upgrade pip
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then pip install --upgrade pip setuptools --user; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install --upgrade pip setuptools; fi
  - pip install -r Requirements/requirements-dev-local.txt

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then dev/run_tests.bat; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then dev/run_linters.bat; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dev/run_tests.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dev/run_linters.sh; fi

after_success:
  - codecov
