language: python

cache: pip

branches:
  only:
  - master
  - /^v.*$/     # Tags need to start with 'v' to be recognized for deployment
  - test-stages

matrix:
  include:
  - name: "Linux, Python 3.6"
    os: linux
    dist: xenial
    python: "3.6"
  - name: "Linux, Python 3.7.3"
    os: linux
    dist: xenial
    python: "3.7.3"
  - name: "Windows, Python 3.7.3 (x64)"
    os: windows
    language: sh
    python: "3.7.3"
    before_install: choco install python --version=3.7.3
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
- python --version --version
- python -m pip install --upgrade pip setuptools wheel
# don't use the '--upgrade' to not upgrade pinned requirements with generic ones
- pip install -r Requirements/requirements-dev-for-release.txt
- pip install -r Requirements/requirements-dev-local.txt

# Capture some information
- pip list

script:
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then dev/run_tests.bat; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then dev/run_linters.bat; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dev/run_tests.sh; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dev/run_linters.sh; fi

after_success:
- codecov

# Check the Deployment Conditions
- echo TRAVIS_BRANCH $TRAVIS_BRANCH
- echo DEPLOY_ENABLED $DEPLOY_ENABLED
- echo TRAVIS_TAG $TRAVIS_TAG

jobs:
  include:
    - # Just some cases
      if: $DEPLOY_ENABLED = "True"
      stage: deploy
      script: echo $name, $DEPLOY_ENABLED

