# https://docs.travis-ci.com/user/job-lifecycle/

language: python

env:
- TESTING=UNIT_TESTS
- TESTING=INTEGRATION_TESTING

cache: pip

#matrix:
#  include:
#  - name: "Linux, Python 3.7 - Postgres"
#    os: linux
#    dist: xenial
#    python: "3.7"
#    env: DJANGO_DB=POSTGRES
#  - name: "Linux, Python 3.8 - Sqlite"
#    os: linux
#    dist: xenial
#    python: "3.8"
#    env: DJANGO_DB=SQLITE

jobs:
  fast_finish: true
  include:
    - python: "3.7"
      env: TEST_PYTHON=3.7
    - python: "3.8"
      env: TEST_PYTHON=3.8

  allow_failures:
    - python: "3.6"
      env: 
      - TEST_PYTHON=3.6
      - FORCE_FAIL=TRUE

before_cache:
- echo PHASE - before_cache

after_cache:
- echo PHASE - after_cache

before_install:
- echo PHASE - before_install
- printenv

install:
- echo PHASE - install

after_install:
- echo PHASE - after_install

before_script:
- echo PHASE - before_script

script:
- echo PHASE - script
- if [ "$FORCE_FAIL" = "TRUE" ]; then exit 1; fi

after_script:
- echo PHASE - after_script

after_success:
- echo PHASE - after_success

after_failure:
- echo PHASE - after_failure

before_deploy:
- echo PHASE - before_deploy

deploy:
- echo PHASE - deploy

after_deploy:
- echo PHASE - after_deploy
