# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          curl -H "Accept: application/vnd.github.sombra-preview+json" https://api.github.com/ericziethen/test_travis_ci/settings/interaction_limits
          curl -H "Accept: application/vnd.github.sombra-preview+json" https://github.com/ericziethen/test_travis_ci/settings/interaction_limits
          echo Add other actions to build,
          echo test, and deploy your project.
          curl --version
          curl \
            -X PUT \
            -H "Accept: application/vnd.github.sombra-preview+json" \
            https://api.github.com/ericziethen/test_travis_ci/settings/interaction_limits \
            -d '{"limit":"collaborators_only"}'
