# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # # # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
      #     curl --version

      # - name: curl - get - 1
      #   run: |
      #     curl -u ericziethen:f18f342655b399820924d358f5b5c8de3973bf9d -H "Accept: application/vnd.github.sombra-preview+json" https://api.github.com/repos/ericziethen/test_travis_ci/interaction-limits

      # - name: curl - get - 2
      #   run: |
      #     curl -H "Accept: application/vnd.github.sombra-preview+json" https://api.github.com/repos/ericziethen/test_travis_ci/interaction-limits

      # - name: curl - get - 3
      #   env:
      #     SUPER_SECRET: ${{ secrets.TEST_SECRET }}
      #   run: |
      #     curl -u ericziethen:$SUPER_SECRET -H "Accept: application/vnd.github.sombra-preview+json" https://api.github.com/repos/ericziethen/test_travis_ci/interaction-limits

      # - name: curl - set - 1
      #   env:
      #     SUPER_SECRET: ${{ secrets.TEST_SECRET }}
      #   run: |
      #     curl -u ericziethen:$SUPER_SECRET -X PUT -H "Accept: application/vnd.github.sombra-preview+json" https://api.github.com/repos/ericziethen/test_travis_ci/interaction-limits -d '{"limit":"collaborators_only"}'

      # - name: curl - get - 4
      #   env:
      #     SUPER_SECRET: ${{ secrets.TEST_SECRET }}
      #   run: |
      #     curl -u ericziethen:$SUPER_SECRET -H "Accept: application/vnd.github.sombra-preview+json" https://api.github.com/repos/ericziethen/test_travis_ci/interaction-limits

      # - name: curl - get - 5 (GITHUB_TOKEN)
      #   env:
      #     SUPER_SECRET: ${{ secrets.GITHUB_TOKEN  }}
      #   run: |
      #     curl -u ericziethen:$SUPER_SECRET -H "Accept: application/vnd.github.sombra-preview+json" https://api.github.com/repos/ericziethen/test_travis_ci/interaction-limits

      # - name: Secret Command - Echo
      #   env:
      #     SUPER_SECRET: ${{ secrets.SECRET_COMMAND_CURL_VERSION  }}
      #   run: |
      #     echo "$SUPER_SECRET"

      # - name: Secret Command - Run Eval
      #   env:
      #     SUPER_SECRET: ${{ secrets.SECRET_COMMAND_CURL_VERSION  }}
      #   run: |
      #     eval "$SUPER_SECRET"


      - name: Get Interaction Limits - Using Secret Token
        env:
          SUPER_SECRET: ${{ secrets.SECRET_TOKEN_ADMIN_ORG_RW_ONLY }}
        run: |
          echo The Secret is "$SUPER_SECRET"
          curl -u ericziethen:$SUPER_SECRET -H "Accept: application/vnd.github.sombra-preview+json" https://api.github.com/repos/ericziethen/test_travis_ci/interaction-limits

      - name: Clear Interaction Limits - Using Secret Token
        env:
          SUPER_SECRET: ${{ secrets.SECRET_TOKEN_ADMIN_ORG_RW_ONLY }}
        run: |
          echo The Secret is "$SUPER_SECRET"
          curl -u ericziethen:$SUPER_SECRET -X PUT -H "Accept: application/vnd.github.sombra-preview+json" https://api.github.com/repos/ericziethen/test_travis_ci/interaction-limits -d '{}'

      - name: Set Interaction Limits - Using Secret Token
        env:
          SUPER_SECRET: ${{ secrets.SECRET_TOKEN_ADMIN_ORG_RW_ONLY }}
        run: |
          echo The Secret is "$SUPER_SECRET"
          curl -u ericziethen:$SUPER_SECRET -X PUT -H "Accept: application/vnd.github.sombra-preview+json" https://api.github.com/repos/ericziethen/test_travis_ci/interaction-limits -d '{"limit":"collaborators_only"}'

      - name: Get Interaction Limits - Using Secret Token
        env:
          SUPER_SECRET: ${{ secrets.SECRET_TOKEN_ADMIN_ORG_RW_ONLY }}
        run: |
          echo The Secret is "$SUPER_SECRET"
          curl -u ericziethen:$SUPER_SECRET -H "Accept: application/vnd.github.sombra-preview+json" https://api.github.com/repos/ericziethen/test_travis_ci/interaction-limits
